#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
	/home/tv/cfg/comskip

# copy config
[[ ! -e /home/tv/cfg/dvr/config ]] && \
	(mkdir -p /home/tv/cfg/dvr/config && cp /defaults/7a5edfbe189851e5b1d1df19c93962f0 /home/tv/cfg/dvr/config/7a5edfbe189851e5b1d1df19c93962f0)
[[ ! -e /home/tv/cfg/comskip/comskip.ini ]] && \
	cp /defaults/comskip.ini.org /home/tv/cfg/comskip/comskip.ini

# permissions
chown -R abc:abc \
	/home/tv/cfg/ \
	/picons
